### ISSUE TITLE
Optimize, Compress, and Resize Images

### ISSUE THREAD

**Issue by dshepsis** [dshepsis/OkamiMap#2]
The images are currently uncompressed PNG's captured from in-game. They are very large in terms of network size. I will compress them into webp's at full resolution (for use on the table preview) and significantly reduced resolution (for use on the leaflet map preview).

**Comment by zysim** [comment]
FWIW this'll be solved with #26

**Comment by zysim** [comment]
Looking back at this; isn't this solved already? If not, there's that script I wrote that we could use to compress everything as needed.

**Comment by dshepsis** [comment]
I originally wanted to have smaller versions of the images for the leaflet map, but I'm not really sure that's necessary at this point. I'll close this for now and maybe when things progress further we can revisit the costs/benefits.
