### ISSUE TITLE
Mayyyyyybe Have A Code Style Set (E.g. Prettier)

### ISSUE THREAD

**Issue by zysim** [dshepsis/OkamiMap#20]
Just in case situations arise where we get commits where one line keeps having a semicolon removed and readded, or more likely in my case, polluting a commit with a reformatting of a whole file that you've done. This isn't a big deal, of course; simple 'yes/no' and we're done.

**Comment by dshepsis** [comment]
Feel free to select a linter and/or formatter for the project. I've used them in the past but didn't consider it necessary when initially setting up this project. Just make sure you include any necessary config files within the repo, and maybe add a "Contributions" section to the readme to instruct future contributors/maintainers exactly how to set up their editor.

**Comment by zysim** [comment]
For sure

**Comment by zysim** [comment]
#21

**Comment by dshepsis** [comment]
Fixed by #21
