### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by dshepsis** [dshepsis/OkamiMap#27]
Add styles for dark mode on the table pages. This should support both OS-side darkmode preferences as well as allow the user to change some on-site settings or press a button to switch between light and dark mode. Dark mode may be preferred as the default.

**Comment by zysim** [comment]
> OS-side darkmode preferences
There's such a thing?
Also, basically this is just, like, `run WriteCss.exe`, right?

**Comment by zysim** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme
Woah
You learn something new every day 🌈⭐

**Comment by zysim** [comment]
Went down a rabbit hole and I've come across this page:
https://color-scheme-demo.glitch.me/
Or well, I got to this page from the article mentioned, which links to that page. It's the very first link in the page ([this one](https://web.dev/color-scheme)). Also, the [second link](https://webaim.org/resources/contrastchecker/?fcolor=0000EE&bcolor=000000) on that page should be useful too, to determine if the colour scheme we come up with is all nice 'n' accessible.
